services:
  # Frontend service
  frontend:
    build:
      context: ./ur
    env_file:
      - ./.env
    ports:
      - "5555:5555"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  # Backend service
  backend:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      context: ./server
    env_file:
      - ./.env
    ports:
      - "4444:4444"
    restart: unless-stopped
    networks:
      - app-network

# Create a custom network
networks:
  app-network:
    driver: bridge
